titleAndCommits: true
allowMergeCommits: true
allowRevertCommits: true

types:
  - "docs"
  - "feat"
  - "fix"
  - "refactor"
  - "revert"
  - "sponsors"
  - "version"

scopes:
  - "bolt"
  - "consul"
  - "docker"
  - "nomad"
  - "vagrant"
  - "vault"
  - "waypoint"
