# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    # Configure the VM options.
    config.vm.box = "bento/ubuntu-#{ENV['UBUNTU_VERSION']}"
    config.vm.hostname = "debug-server"
  
    # Attach the source code.
    nomad_src = ENV["NOMAD_SRC"]
    if nomad_src != '' 
        config.vm.synced_folder nomad_src, "/home/vagrant/nomad"
    end

    # Attach the enterprise source code.
    nomad_ent_src = ENV["NOMAD_ENT_SRC"]
    if nomad_ent_src != '' 
        config.vm.synced_folder nomad_ent_src, "/home/vagrant/nomad-enterprise"
    end

    # The base hashibox config should not use this ip address.
    # You may need to override this if you are running hashibox
    # at the same time and have more than 3 servers.
    # TODO: Consider supporting an ENV variable for this.
    config.vm.network "private_network", ip: "192.168.60.100"

    # TODO: May need a different RAM/CPU setting for a debug server.
    config.vm.provider "parallels" do |v|
        v.memory = "#{ENV['VAGRANT_SERVER_RAM']}"
        v.cpus = "#{ENV['VAGRANT_SERVER_CPUS']}"
    end

    config.vm.provider "virtualbox" do |v|
        v.memory = "#{ENV['VAGRANT_SERVER_RAM']}"
        v.cpus = "#{ENV['VAGRANT_SERVER_CPUS']}"
    end

    config.vm.provider "vmware_desktop" do |v|
        v.vmx["memsize"] = "#{ENV['VAGRANT_SERVER_RAM']}"
        v.vmx["numvcpus"] = "#{ENV['VAGRANT_SERVER_CPUS']}"

    end
end

  