name: Bug report
description: |
  You are experiencing an issue with HashiBox that is different than the
  documented or expected behavior

body:
  - type: dropdown
    attributes:
      label: What OS are you using?
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true
  - type: textarea
    attributes:
      label: Unexpected behavior
      value: Please write a clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      value: Please indicate the steps needed to reproduce the previously described behavior.
  - type: textarea
    attributes:
      label: Expected behavior
      value: Please describe the behavior you were expected.
  - type: textarea
    attributes:
      label: Logs
      value: You can provide logs (if applicable) so we can better adress your issue.
